# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xpln"
  version "1.0"

  on_macos do
    url "https://github.com/5amCurfew/xpln/releases/download/v1.0/xpln_1.0_darwin_all.tar.gz"
    sha256 "a4853ff428fe71203e288b7cd2daaa5a3e7db0f0aaf20d61aaced04813bbca58"

    def install
      bin.install "xpln"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0/xpln_1.0_linux_arm64.tar.gz"
      sha256 "a30428f44806680a320ac873aaf09102f05b96252d5b572b988c7d3ada2ebb96"

      def install
        bin.install "xpln"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0/xpln_1.0_linux_amd64.tar.gz"
      sha256 "18b1aa8cae51b9ddfd724b687bf46ed09d0e36de597981435ff879312b5cdc4d"

      def install
        bin.install "xpln"
      end
    end
  end
end
