# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orca < Formula
  desc ""
  homepage "https://github.com/5amCurfew/orca"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/orca/releases/download/v0.6.1/orca_Darwin_x86_64.tar.gz"
      sha256 "08043c7b83f466e4609269b46b3e859f288351603342aa0bfd80644ed57b9fe5"

      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/5amCurfew/orca/releases/download/v0.6.1/orca_Darwin_arm64.tar.gz"
      sha256 "72596e5cf87261028e92aaef44e0a4a2b659a5859b00658b827df008c4b1500f"

      define_method(:install) do
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/orca/releases/download/v0.6.1/orca_Linux_x86_64.tar.gz"
      sha256 "65edf790097c66c2ec1998514c0dd22d04b82daae9bb1f6c78de222933b2e188"
      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/orca/releases/download/v0.6.1/orca_Linux_arm64.tar.gz"
      sha256 "794885ae16759fe893f238049aec104f2507b538f362ce68b4977d5d0ee02e06"
      define_method(:install) do
        bin.install "orca"
      end
    end
  end
end
