# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orca < Formula
  desc ""
  homepage "https://github.com/5amCurfew/orca"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/orca/releases/download/v0.3.0/orca_Darwin_x86_64.tar.gz"
      sha256 "cd779008bd4c49da04d92cea4e642418c709f6e6f79be09bbcf33811bfc5982f"

      def install
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/5amCurfew/orca/releases/download/v0.3.0/orca_Darwin_arm64.tar.gz"
      sha256 "fa358e9846cf25b49a614a42d049e59bb2182a8e70291fe665b043ac42f8bd84"

      def install
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/orca/releases/download/v0.3.0/orca_Linux_x86_64.tar.gz"
      sha256 "1f9b8b3c0042f528bbc6e14f7e935ffb6c5ba57b4b8036c8769fd4452a98d5e5"
      def install
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/orca/releases/download/v0.3.0/orca_Linux_arm64.tar.gz"
      sha256 "18a66284e704d47b1e30a08acf42d088a9b19350efa4e882655b3eeb520e3dc2"
      def install
        bin.install "orca"
      end
    end
  end
end
