# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xpln < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xpln"
  version "1.0.5"

  on_macos do
    url "https://github.com/5amCurfew/xpln/releases/download/v1.0.5/xpln_1.0.5_darwin_all.tar.gz"
    sha256 "ec115c7a1ff329c67f93bfae9ce76473223383a33ef9ba92addaa46bd0e78513"

    def install
      bin.install "xpln"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0.5/xpln_1.0.5_linux_arm64.tar.gz"
      sha256 "5c4997ec11de1d2b67bf1e57f72dcdbb737326e299b4fd45981c22f0bef3de61"

      def install
        bin.install "xpln"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0.5/xpln_1.0.5_linux_amd64.tar.gz"
      sha256 "fbedf5d2f41b2fd3a7b512ced2a72934d5b6156174429db5722b7fa0dabdecb7"

      def install
        bin.install "xpln"
      end
    end
  end
end
