# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xpln < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xpln"
  version "1.0.1"

  on_macos do
    url "https://github.com/5amCurfew/xpln/releases/download/v1.0.1/xpln_1.0.1_darwin_all.tar.gz"
    sha256 "d802608b7fb7156fab15e97a951531ac152920c8ad33b95ffa79dc2352d08061"

    def install
      bin.install "xpln"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0.1/xpln_1.0.1_linux_arm64.tar.gz"
      sha256 "3b4dc4455a0bdbeb006e42e6aef869d5bf4a6b93bfd8c511ea440a22eda95187"

      def install
        bin.install "xpln"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xpln/releases/download/v1.0.1/xpln_1.0.1_linux_amd64.tar.gz"
      sha256 "64ba2317c60f1240fa0d99f64ab6f650da93a953eb80e98f6ad9d3cc3d7f39b1"

      def install
        bin.install "xpln"
      end
    end
  end
end
