# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xtkt < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xtkt"
  version "0.0.866"

  on_macos do
    url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.866/xtkt_0.0.866_darwin_all.tar.gz"
    sha256 "407985f6d9d6fbe69df69c50046f467bfb25ca9c1f53396eaea4ec32a1a7bdd7"

    def install
      bin.install "xtkt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.866/xtkt_0.0.866_linux_arm64.tar.gz"
      sha256 "e18df0b1f110fe7d71fddc1e7611428b688c8c90aac7afc211be46d9b8b829fd"

      def install
        bin.install "xtkt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.866/xtkt_0.0.866_linux_amd64.tar.gz"
      sha256 "91d511b1093dacc0d7e3e1cf7ed7f6426598f02f523bc8015ca86022c57d956d"

      def install
        bin.install "xtkt"
      end
    end
  end
end
