# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xtkt < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xtkt"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.3.1/xtkt_Darwin_x86_64.tar.gz"
      sha256 "425b86ad5aced1c062a0c44720436ef43113b53c11ce7df0230069634f935cda"

      def install
        bin.install "xtkt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.3.1/xtkt_Darwin_arm64.tar.gz"
      sha256 "41923edbe968f74d98b941f5d244e954de5746e1e735a3f8cac75c05d12c10cc"

      def install
        bin.install "xtkt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/5amCurfew/xtkt/releases/download/v0.3.1/xtkt_Linux_x86_64.tar.gz"
        sha256 "0c938fe4a547d6c0208e52c43380d1ad8340a195820f2a1df3c700181da1d470"

        def install
          bin.install "xtkt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/5amCurfew/xtkt/releases/download/v0.3.1/xtkt_Linux_arm64.tar.gz"
        sha256 "6001517072e376e8481a35c5780d0b48f33f59a5bbd781dab0576da213ca3bc6"

        def install
          bin.install "xtkt"
        end
      end
    end
  end
end
