# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xtkt < Formula
  desc ""
  homepage "https://github.com/5amCurfew/xtkt"
  version "0.0.3"

  on_macos do
    url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.3/xtkt_0.0.3_darwin_all.tar.gz"
    sha256 "d013aaa740415d810c371033fb74f943dde786426054d0ad7044445417b7c707"

    def install
      bin.install "xtkt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.3/xtkt_0.0.3_linux_arm64.tar.gz"
      sha256 "c977c75fce2d875bea89b058ccb4b88df4b8d2e36b62a0e5592d2fc877f23b4e"

      def install
        bin.install "xtkt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/5amCurfew/xtkt/releases/download/v0.0.3/xtkt_0.0.3_linux_amd64.tar.gz"
      sha256 "9bee29b1ebcb38776f7ac52161f68b3d51af894345b57eea86c010e45e4d7188"

      def install
        bin.install "xtkt"
      end
    end
  end
end
